### ISSUE TITLE
相位剑锋与电弧重合百分百触发

### ISSUE THREAD

**Issue by liveskai** [LightBlueCube/Northstar.FD#1]
![7c10ad5791531a461b38f38ee26a438e](https://github.com/user-attachments/assets/6d3e3651-01b4-447e-ba1c-11134f84c6a6)

**Comment by LightBlueCube** [comment]
这个repo没有做任何改动，基本上是按照上游来的，有可能是上游的问题
你有排除过自己模组或者服务器问题吗，如果可以的话发一下客户端和服务器在这个时间点的日志吧

**Comment by liveskai** [comment]
> 这个repo没有做任何改动，基本上是按照上游来的，有可能是上游的问题 你有排除过自己模组或者服务器问题吗，如果可以的话发一下客户端和服务器在这个时间点的日志吧

![image](https://github.com/user-attachments/assets/810e4b50-d2b1-41bf-8604-f7960a81d7ff)
[nslog2024-11-12 08-57-42.txt](https://github.com/user-attachments/files/17709736/nslog2024-11-12.08-57-42.txt)

**Comment by liveskai** [comment]
[服务端nslog2024-11-11 19-12-04.txt](https://github.com/user-attachments/files/17709748/nslog2024-11-11.19-12-04.txt)
服务器不会炸

**Comment by liveskai** [comment]
![image](https://github.com/user-attachments/assets/4888ba39-30ac-43da-ac0a-004ecffdc308)
不剑锋也会炸

**Comment by LightBlueCube** [comment]
检查了更改过的文件并不包含任何的浪人技能或者武器，根据情况描述判断应该着重检查一下是否为客户端安装的第三方模组的问题
