### ISSUE TITLE
中途加入的玩家不会成为NPC的目标

### ISSUE THREAD

**Issue by liveskai** [LightBlueCube/Northstar.FD#2]
类似双相位bug

**Comment by LightBlueCube** [comment]
需要提供更多信息，问题表述不清晰

**Comment by liveskai** [comment]
> 需要提供更多信息，问题表述不清晰

NPC无视中途加入的玩家，相当于玩家卡了浪人双相位BUG

**Comment by liveskai** [comment]
打扰了，是我的问题，复活时有player.SetNoTarget( true )，后续的代码我动了一下，没有使用另一个函数
